- name: Copy bin files
  copy:
    src: bin/
    dest: /bin/
    owner: root
    group: root
    mode: '0755'

- name: Copy Config boilerplates
  copy:
    src: config/
    dest: "{{ foundation_supportroot }}/config/"
    owner: "{{ foundation_appuser }}"
    group: "{{ foundation_appuser }}"
