---
- include_tasks: copy_files.yml
- include_tasks: apt.yml
  vars:
    apt_key_urls:
      - https://nginx.org/keys/nginx_signing.key
    apt_repositories:
      - "deb https://nginx.org/packages/ubuntu/ focal nginx"
      - "deb-src https://nginx.org/packages/ubuntu/ focal nginx"
    apt_packages:
      - nginx
- include_tasks: disable_services.yml
  vars:
    service_list:
      nginx

- name: Setup required Nginx folder structure
  file:
    path: "{{item}}"
    owner: "{{ syndrome_appuser }}"
    group: "{{ syndrome_appuser }}"
    state: directory
  with_items:
    - /var/cache/nginx/
    - /var/www/
    - /etc/nginx/sites-enabled/
    - /var/log/nginx/


- name: Copy nginx config templates in place.
  template:
    src: "{{item}}.j2"
    dest: "/etc/nginx/{{item}}"
    owner: root
    group: "root"
    mode: '0644'
  with_items:
    - "nginx.conf"
    - "conf.d/default_server.conf"

- name: Remove unnecessary files
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - "/etc/nginx/sites-enabled/vhosts.conf"
    - "/workspace/run/nginx.pid"
    - "/etc/nginx/conf.d/default.conf"

- name: Basic HTML Site
  copy:
    src: 'www/'
    dest: /var/www/
    owner: appbot
    group: appbot

- include_tasks: "only-docker.yml"
  when: packer_build_name == "docker"

- include_tasks: "only-ami.yml"
  when: packer_build_name == "ami"

